services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
